### PR TITLE
Deprecate non-specification field

### PR DESCRIPTION
**Pull request by ForestEckhardt**
## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ryanmoran** [comment]
It may not appear to be used in `packit` or by our buildpacks, but `jam` uses this field [here](https://github.com/paketo-buildpacks/jam/blob/d3e4a29ebe31a86a80cb9f61d5b01fe47aea785c/internal/buildpack_inspector.go#L98). Maybe we can figure out how not to use this in `jam` and then we can remove it.

**Comment by ForestEckhardt** [comment]
Interesting because as far as I can figure from the spec the buildpack table has no SHA field.

**Comment by ryanmoran** [comment]
Its not used to read out a value from the `buildpack.toml`. Its just used to hold the value between that point in the `jam` code and the formatter.

**Comment by ForestEckhardt** [comment]
@ryanmoran Here is a PR to remove the use of the `Buildpack.SHA256` field from `jam` https://github.com/paketo-buildpacks/jam/pull/17

**Comment by ryanmoran** [comment]
Are you planning to bump the major version of `packit` when you remove this?

**Comment by ForestEckhardt** [comment]
I hadn't really thought about how I would classify the bump. I think that by definition it would have to be but the field was never parsed it was just part of the structure. It feels a little silly to have a major bump over such a small change.

**Comment by ryanmoran** [comment]
Yes. But strictly speaking, its a backwards-incompatible change. Maybe you should leave the field and just mark it as deprecated which is what we have done in the past. Then, when we get to a point where a major version bump feels warranted because of other, more substantial changes, we can remove it.

**Comment by ForestEckhardt** [comment]
I think that is fair. We can still go forward with the Jam change as well.

**Review by ryanmoran — APPROVED** [review]

**Pull request merged**
