### PR TITLE
Change dash to underscore

### PR DESCRIPTION
**Pull request by ForestEckhardt**
- Changes dash to underscore to reflect the already existing pattern set
by include_files and pre_package

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
PRs also need to be made against the following repos that set default versions:
- [ ] MRI
- [ ] Bundler
- [ ] PHP-Dist
- [ ] PHP-Composer
- [ ] NGINX
- [ ] Node-engine
- [ ] Yarn
- [ ] Go-dist

**Comment by ryanmoran** [comment]
This differs from what the `libpak` buildpacks do. Do we want to rethink aligning with them for organizational consistency?

**Comment by ForestEckhardt** [comment]
@ryanmoran What do the `libpak` buildpacks do?

**Comment by ryanmoran** [comment]
They use dashes like `pre-package`, `include-files`, and `default-versions`. I get making it consistent, but maybe we should go all the way to aligning more with the rest of the org.

**Comment by ForestEckhardt** [comment]
Ahhhh I thought that the underscores were the standard. I am more than happy to move in the other direction.

**Comment by ForestEckhardt** [comment]
I am going to close this PR and I will open another one different one where I have switched the dashes for underscores.

**Pull request closed without merging**
