### PR TITLE
Introduce fs.FileExists

### PR DESCRIPTION
**Pull request by andymoe**
## Summary
Adds a the method `FileExists` to the `fs` sub package. This is code we found ourselves needing more than a couple places in the `conda-env-update` buildpack.

Also alphabetized suite call order in `fs/init_test.go`

## Use Case
```
lockfilePresent, err := fs.FileExists("/path/to/lockfile.txt") 
if err != nil {
  panic("Et tu, lockfile?")
}

if lockfilePresent {
  fancypackage.DoFancyThingsWithLockfile()
}
```

*Note:* this PR does not have test cases for using this method against a directory. While we have more test coverage than `libbuildpack` does I've not been able to figure out how to correctly test this case properly. The additional (broken/wrong) tests for a fs.FileExists(`/my/missing/directory`) are on [this branch](https://github.com/paketo-buildpacks/packit/compare/main...andymoe:add-fs-file-exists-broken-dir-tests#diff-a6a98d8667a3f799f0cf084566a573bea6980266bf5f4c47513872898b72e2deR73-R109) if you have ideas/feedback.

### CODE REVIEW

**Comment by ryanmoran** [comment]
I'd like to see a couple changes:
1. Can we change the method to `fs.Exists` since it should apply to more than just files?
2. I've figured out the issues with the directory tests. Mostly it was caused by the definition of `subDir` in the wrong scope. Here is a diff of the changes I made:
```diff
                context("when we are testing for a directory", func() {
-                       var subDir = filepath.Join(dirPath, "sub-dir")
+                       var subDir string
+
+                       it.Before(func() {
+                               subDir = filepath.Join(dirPath, "sub-dir")
+                               Expect(os.Mkdir(subDir, os.ModePerm)).To(Succeed())
+                       })
+
                        context("and a directory exists", func() {
                                it("returns true", func() {
-                                       Expect(os.Mkdir(subDir, os.ModePerm)).To(Succeed())
-                                       Expect(fs.FileExists(dirPath)).To(BeTrue())
+                                       Expect(fs.FileExists(subDir)).To(BeTrue())
                                })
                        })
+
                        context("when the directory does not exist", func() {
                                it.Before(func() {
-                                       Expect(os.RemoveAll(dirPath)).To(Succeed())
+                                       Expect(os.RemoveAll(subDir)).To(Succeed())
                                })

                                it("returns false", func() {
-                                       Expect(fs.FileExists(dirPath)).To(BeFalse())
+                                       Expect(fs.FileExists(subDir)).To(BeFalse())
                                })
                        })

@@ -97,12 +104,10 @@ func testFileExists(t *testing.T, context spec.G, it spec.S) {
                                        Expect(os.Chmod(dirPath, os.ModePerm)).To(Succeed())
                                })

-                               // With this setup we keep getting nil error which I don't understand.
-                               // I'm clearly missing something.
                                it("returns false and an error", func() {
-                                       exits, err := fs.FileExists(subDir)
-                                       Expect(err.Error()).To(ContainSubstring("<syscall.Errno>0xd"))
-                                       Expect(exits).To(BeFalse())
+                                       exists, err := fs.FileExists(subDir)
+                                       Expect(err).To(MatchError(ContainSubstring("permission denied")))
+                                       Expect(exists).To(BeFalse())
                                })
                        })
                })
```

**Comment by andymoe** [comment]
Thanks! I'll get this fixed up. I really got myself confused with the scoping there...

**Comment by ForestEckhardt** [comment]
@andymoe @ryanmoran Is the only thing that this is waiting on changing the name of the function to be more generic? I would love to move this along because the ask seems relatively straight forward.

**Comment by andymoe** [comment]
Yeah, sorry. I had some issues with my tests etc too and I never got back
to it and sorted it out locality.

**Comment by ForestEckhardt** [comment]
@andymoe Bump

**Comment by sophiewigmore** [comment]
Closing out this PR as it has not been updated since April. Feel free to re-open if you want to keep working on this

**Comment by sophiewigmore** [comment]
Drafting this for now since there has not been a code update since April.

**Pull request closed without merging**
