### PR TITLE
Moves the default tag next to the type name

### PR DESCRIPTION
**Pull request by ForestEckhardt**
## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
@ryanmoran Does this more scratch your itch.

Also does this necessitate a minor bump?

**Comment by ryanmoran** [comment]
LGTM. Why do you think this requires a minor bump?

**Comment by ForestEckhardt** [comment]
We are changing the format of log output that is tested for in some of our buildpacks.

**Comment by ryanmoran** [comment]
I'm not sure I think of the log output as part of the public API.

**Comment by ForestEckhardt** [comment]
Hmmm I guess that is true. There is no change to the code api just the output. I am comfortable with a patch then!

**Review by ryanmoran — APPROVED** [review]

**Pull request merged**
