### PR TITLE
add sbom field to buildpack.toml (Buildpack API 0.7)

### PR DESCRIPTION
**Pull request by robdimsdale**
Signed-off-by: Rob Dimsdale-Zucker <rdimsdale@vmware.com>

## Summary
As part of implementing the [RFC for Syft/CycloneDX](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0038-cdx-syft-sbom.md) we need to add a field to the buildpack.toml as described in the [upstream RFC](https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md).

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
@paketo-buildpacks/tooling-maintainers As you can see, there were 2 representations of the `buildpack.toml` that needed to change. I don't love that we have two structs inside of packit representing ostensibly the same thing. Can anyone shed light on why we have two? I know that some of the things in `cargo` aren't spec'd (e.g. dependency constraints); but I'm wondering if we can de-duplicate the representation of fields like `buildpack.licenses` and buildpack.sbom`.

**Comment by fg-j** [comment]
Per [this update in the CNB slack](https://buildpacks.slack.com/archives/C01DE41JHAA/p1637254357031300) the field will need to be renamed.

**Comment by robdimsdale** [comment]
> Per [this update in the CNB slack](https://buildpacks.slack.com/archives/C01DE41JHAA/p1637254357031300) the field will need to be renamed.

Done.

**Comment by sophiewigmore** [comment]
We were holding back on the release of this PR until buildpack API 0.7 became available. It is available now, so I think we can merge this in unless @ForestEckhardt or @ryanmoran have any other concerns.

**Review by sophiewigmore — APPROVED** [review]

**Review by ForestEckhardt — APPROVED** [review]

**Comment by ForestEckhardt** [comment]
Nothing form me.

**Comment by ForestEckhardt** [comment]
> @paketo-buildpacks/tooling-maintainers – minor version bump?

I don't have strong opinions minor sounds right to me

**Pull request merged**
